version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: bash -c "apt-get update && apt-get install -y libzip-dev && docker-php-ext-install zip pdo pdo_mysql && php-fpm"
